### PR TITLE
Enhance UI and add chat history storage: Improve Pop-up UI, Chat UI, …

### PR DESCRIPTION
**Pull request by CoderSwarup**
# Feature
1. Pop-up UI: Refined the design and layout of the pop-up component to improve usability and accessibility.
2. Chat UI: Updated the chat interface, including better message organization, error handling, and the addition of avatars
3. Chat History Storage: Implemented a system to store previous chat interactions, allowing users to revisit past messages for continuity.

https://github.com/user-attachments/assets/d5ca2e8e-b62a-4e12-a477-2dcec04d8211

### CODE REVIEW

**Comment by piyushgarg-dev** [comment]
Wow, Great job.
Can you remove that user and assistant avatar from chat? 
Let's keep that clean only.

Otherwise great work

**Comment by CoderSwarup** [comment]
> Wow, Great job. Can you remove that user and assistant avatar from chat? Let's keep that clean only.
> 
> Otherwise great work

Sure 😊 
Thank 😍

**Comment by piyushgarg-dev** [comment]
Also, it is crashing for me

**Comment by CoderSwarup** [comment]
> Also, it is crashing for me

I thinks it will crash at a time of api response generation?

**Comment by piyushgarg-dev** [comment]
Yes this is great, please push the code @CoderSwarup

**Comment by piyushgarg-dev** [comment]
One more feedback, let's remove the sidebar. Loading the chat from history when user visits same problem is great.

**Pull request closed without merging**
